workspace:
  base: /go
  path: src/github.com/developgo/skm
  
pipeline:
  fetch:
    image: docker:git
    commands:
      - git fetch --tags
  test:
    image: golang:latest
    commands:
      - go vet
      - go test -v -cover
      - go clean
  build:
    image: golang:latest
    commands:
      - go build -ldflags "-X main.Version=${DRONE_TAG}" -o skm
      - go test -v
      - go clean
  release:
    image: golang:latest
    secrets: [github_token]
    commands:
      - cd cmd/skm 
      - curl -sL https://git.io/goreleaser | bash
    when:
      event: tag
