workspace:
  base: /go
  path: src/github.com/developgo/skm
  
pipeline:
  fetch:
    image: docker:git
    commands:
      - git fetch --tags

  release:
    when:
      event:
        - tag
    image: golang:latest
    secrets: [github_token]
    commands:
      - export GO111MODULE="on"
      - go mod download
      - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin v1.15.0
      - golangci-lint run --fast
